### PR TITLE
Candidate for new `master`

### PR DESCRIPTION
**Pull request by savetheclocktower**
This PR proves that the state of #13 is identical to what I've done here: _keep_ all commits, except explicitly revert the parts of #1 that change the source code.

I have more faith that this will merge cleanly into `master` than #13 — which I made by starting from an earlier commit and cherry-picking everything except for #1.

@mauricioszabo, my reasoning here is that

* we proved that these code changes were (somehow) the source of renderer process crashes in Pulsar while running package and editor tests in CI;
* as I understand it, the changes in #1 don't do much on their own to achieve compatibility with newer Electron and newer V8 — we'd want the more comprehensive N-API stuff present in #10.

Once we merge this, we can point Pulsar's `package.json` to our copy of `superstring` for the first time — as has been made necessary by the fact that we must explicitly build our own copy of `libiconv` on macOS.

### CODE REVIEW

**Comment by savetheclocktower** [comment]
Also happy to adopt the CI stuff recently suggested by @DeeDeeG, though I'm happy to back it out again if they think it should be part of a separate PR.

**Review by mauricioszabo — APPROVED** [review]
Let's merge this, sure!

Indeed, it's our best course of action to just try the N-API version instead.

**Comment by savetheclocktower** [comment]
Failures on Node 18 (on all platforms) are not necessarily expected, but not surprising either.

Failures on macOS on Node 14 are acceptable — two specs are failing on an obscure encoding.

Landing this!

**Comment by DeeDeeG** [comment]
The Node 18 failures are from reverting the code we cherry-picked from NAN, unfortunately :/.

**Pull request merged**
